export const programmaticPages = [
  {
    slug: "png-to-svg",
    title: "PNG to SVG Converter",
    description: "Convert PNG artwork, logos, jersey graphics, and print files into clean SVG vectors with DesaynClaw's AI vector tracer.",
    audience: "print shops, logo designers, Cricut users, and sublimation businesses",
    intent: "Convert transparent or raster PNG artwork into scalable SVG files for print, cutting, and production.",
    primaryUseCase: "Turn low-resolution PNG designs into editable, print-ready SVG output.",
    features: ["AI vector tracing", "SVG download", "Background cleanup", "Logo and design enhancement"],
    faqs: [
      { question: "Can DesaynClaw convert PNG logos to SVG?", answer: "Yes. DesaynClaw traces PNG artwork and exports SVG files suitable for design cleanup, printing, cutting, and production workflows." },
      { question: "Is PNG to SVG useful for sublimation?", answer: "Yes. Vector SVG output helps print shops scale artwork cleanly before preparing sublimation, DTF, screen print, or sticker files." },
    ],
    relatedSlugs: ["jpg-to-svg", "logo-to-svg", "cricut-svg"],
  },
  {
    slug: "jpg-to-svg",
    title: "JPG to SVG Converter",
    description: "Vectorize JPG artwork into clean SVG files for logos, jersey designs, Cricut projects, signs, and print production.",
    audience: "designers and print shops working with flattened JPG artwork",
    intent: "Recover scalable vector output from compressed JPG artwork.",
    primaryUseCase: "Convert customer-supplied JPG logos or designs into editable SVG assets.",
    features: ["JPG vectorization", "AI cleanup", "SVG export", "Print-ready workflow"],
    faqs: [
      { question: "Can a JPG become a real SVG?", answer: "DesaynClaw traces the visible shapes in a JPG and converts them into SVG vector paths that can be edited or prepared for production." },
      { question: "Does JPG compression affect tracing?", answer: "Heavy compression can reduce edge quality, but AI cleanup and upscaling can improve the source before SVG export." },
    ],
    relatedSlugs: ["png-to-svg", "image-upscaler", "ai-vector-tracer"],
  },
  {
    slug: "logo-to-svg",
    title: "Logo to SVG Converter",
    description: "Convert customer logos into scalable SVG vectors for print shops, designers, Cricut cuts, embroidery prep, and sign making.",
    audience: "logo designers, print shops, embroidery digitizers, and sign makers",
    intent: "Convert raster logos into clean vector files without rebuilding them manually.",
    primaryUseCase: "Prepare logos for scaling, printing, cutting, and production handoff.",
    features: ["Logo vector tracing", "Edge cleanup", "Transparent output", "SVG download"],
    faqs: [
      { question: "Can I vectorize a low-resolution logo?", answer: "Yes. DesaynClaw can upscale and trace low-resolution logo artwork to create a cleaner SVG starting point." },
      { question: "Is SVG the right format for logo production?", answer: "SVG is ideal for scalable web, print prep, cutting machines, and handoff to vector editing tools." },
    ],
    relatedSlugs: ["vectorize-logo", "jpg-to-svg", "embroidery-vector"],
  },
  {
    slug: "vectorize-logo",
    title: "Vectorize Logo Online",
    description: "Use AI to vectorize logos from screenshots, mockups, PNGs, and JPGs into SVG files for production workflows.",
    audience: "busy print shops and designers who receive imperfect customer logo files",
    intent: "Create a scalable logo vector from imperfect raster artwork.",
    primaryUseCase: "Clean up client-supplied logos before sublimation, DTF, screen print, embroidery, or signage.",
    features: ["Logo cleanup", "AI vector tracer", "SVG export", "Production-ready scaling"],
    faqs: [
      { question: "What files can I upload?", answer: "You can upload common image formats such as PNG and JPG, then use DesaynClaw to trace and prepare an SVG output." },
      { question: "Will the SVG be editable?", answer: "The exported SVG is made from vector paths, which can be opened in compatible vector design software for refinement." },
    ],
    relatedSlugs: ["logo-to-svg", "ai-vector-tracer", "sublimation-vector"],
  },
  {
    slug: "ai-vector-tracer",
    title: "AI Vector Tracer",
    description: "Trace raster artwork into SVG vectors with AI for sublimation, apparel, signage, stickers, and design production.",
    audience: "designers, print shops, and production teams",
    intent: "Automate the first pass of vector tracing while preserving a clean production workflow.",
    primaryUseCase: "Move from raster upload to usable SVG without redrawing the design by hand.",
    features: ["AI tracing", "SVG export", "Preview workflow", "Production-focused cleanup"],
    faqs: [
      { question: "What is an AI vector tracer?", answer: "An AI vector tracer detects shapes and edges in raster artwork, then converts them into scalable vector paths." },
      { question: "Who is DesaynClaw built for?", answer: "DesaynClaw is built for print shops, apparel designers, sublimation businesses, Cricut users, sign makers, and similar production workflows." },
    ],
    relatedSlugs: ["png-to-svg", "logo-to-svg", "sublimation-vector"],
  },
  {
    slug: "background-remover",
    title: "AI Background Remover",
    description: "Remove backgrounds from logos, product photos, jersey mockups, and print artwork to create transparent PNG files.",
    audience: "print shops, online sellers, designers, and sublimation businesses",
    intent: "Create clean transparent artwork before tracing, upscaling, or preparing print files.",
    primaryUseCase: "Remove noisy or unwanted image backgrounds in seconds.",
    features: ["AI subject cutout", "Transparent PNG", "Logo cleanup", "Print prep workflow"],
    faqs: [
      { question: "Can I remove a logo background?", answer: "Yes. DesaynClaw can remove backgrounds from logo images and prepare transparent files for the next production step." },
      { question: "Can background removal help vector tracing?", answer: "Yes. Removing backgrounds first can make the artwork cleaner and easier to trace into SVG." },
    ],
    relatedSlugs: ["png-to-svg", "logo-to-svg", "image-upscaler"],
  },
  {
    slug: "image-upscaler",
    title: "AI Image Upscaler",
    description: "Upscale low-resolution logos, jersey graphics, and customer artwork before print production or vector tracing.",
    audience: "print shops, apparel designers, and ecommerce sellers",
    intent: "Improve low-resolution source files before output, tracing, or production handoff.",
    primaryUseCase: "Turn small or blurry artwork into a better source for design cleanup.",
    features: ["4K upscaling", "Logo enhancement", "JPG and PNG support", "Print workflow support"],
    faqs: [
      { question: "Should I upscale before vectorizing?", answer: "Upscaling can improve edge clarity, especially when the source artwork is small, compressed, or blurry." },
      { question: "Can DesaynClaw upscale logos?", answer: "Yes. DesaynClaw can enhance low-resolution logos before tracing or print preparation." },
    ],
    relatedSlugs: ["jpg-to-svg", "logo-to-svg", "ai-vector-tracer"],
  },
  {
    slug: "basketball-logo-to-svg",
    title: "Basketball Logo to SVG",
    description: "Convert basketball team logos and jersey artwork into SVG vectors for uniforms, sublimation, stickers, and print production.",
    audience: "sportswear designers, team uniform shops, and basketball jersey makers",
    intent: "Prepare basketball logos and graphics for scalable jersey production.",
    primaryUseCase: "Vectorize team logos for jersey layouts, sublimation panels, and print-ready artwork.",
    features: ["Sports logo tracing", "SVG export", "Jersey artwork workflow", "Scale-safe output"],
    faqs: [
      { question: "Can I use this for team jersey designs?", answer: "Yes. DesaynClaw is built for apparel and sports jersey production workflows, including basketball graphics." },
      { question: "Does SVG help jersey printing?", answer: "SVG artwork can be scaled for different jersey sizes and panels without the pixelation common in raster files." },
    ],
    relatedSlugs: ["sublimation-vector", "logo-to-svg", "vectorize-logo"],
  },
  {
    slug: "sublimation-vector",
    title: "Sublimation Vector Tool",
    description: "Create scalable SVG artwork for sublimation printing, jersey designs, apparel mockups, and print shop production.",
    audience: "sublimation businesses, apparel designers, and uniform print shops",
    intent: "Prepare scalable vector artwork for sublimation production.",
    primaryUseCase: "Convert raster jersey graphics and customer artwork into production-friendly vector assets.",
    features: ["Sublimation artwork tracing", "SVG output", "Logo cleanup", "Flat file preparation"],
    faqs: [
      { question: "Why use vectors for sublimation?", answer: "Vectors keep artwork scalable and easier to edit while preparing jersey panels, apparel graphics, or production templates." },
      { question: "Can DesaynClaw extract jersey designs?", answer: "Yes. DesaynClaw is designed around sublimation design extraction and vector tracing workflows." },
    ],
    relatedSlugs: ["basketball-logo-to-svg", "ai-vector-tracer", "dtf-printing-vector"],
  },
  {
    slug: "embroidery-vector",
    title: "Embroidery Vector Prep",
    description: "Prepare clean vector logo artwork before embroidery digitizing, patch production, and apparel decoration.",
    audience: "embroidery shops, apparel decorators, and logo designers",
    intent: "Clean and vectorize logo artwork before sending it into embroidery digitizing workflows.",
    primaryUseCase: "Create a cleaner SVG reference for embroidery digitizers and production teams.",
    features: ["Logo cleanup", "SVG export", "Edge refinement", "Production handoff"],
    faqs: [
      { question: "Is SVG the same as an embroidery file?", answer: "No. SVG is not a stitch file, but it is a clean vector source that can help before embroidery digitizing." },
      { question: "Can this help with patch artwork?", answer: "Yes. Clean vector artwork is useful when preparing logo patches, badges, and apparel decoration references." },
    ],
    relatedSlugs: ["logo-to-svg", "vectorize-logo", "cricut-svg"],
  },
  {
    slug: "cricut-svg",
    title: "Cricut SVG Converter",
    description: "Convert PNG and JPG artwork into SVG files for Cricut projects, stickers, decals, shirts, and craft production.",
    audience: "Cricut users, craft sellers, designers, and sticker makers",
    intent: "Create scalable SVG files from raster artwork for cutting and craft workflows.",
    primaryUseCase: "Prepare customer artwork or personal designs for Cricut-compatible SVG cleanup.",
    features: ["PNG to SVG", "JPG to SVG", "Transparent background workflow", "Cutting file preparation"],
    faqs: [
      { question: "Can Cricut use SVG files?", answer: "Yes. SVG is a common format for Cricut workflows because it preserves scalable vector shapes." },
      { question: "Should I remove the background first?", answer: "For many designs, removing the background before tracing creates a cleaner SVG starting point." },
    ],
    relatedSlugs: ["png-to-svg", "background-remover", "logo-to-svg"],
  },
  {
    slug: "dtf-printing-vector",
    title: "DTF Printing Vector Prep",
    description: "Prepare customer artwork, logos, and apparel graphics as clean SVG vectors before DTF printing production.",
    audience: "DTF print shops and apparel decorators",
    intent: "Improve incoming artwork before DTF print setup.",
    primaryUseCase: "Convert low-quality customer files into cleaner scalable production assets.",
    features: ["Logo vectorization", "Image cleanup", "SVG export", "Print shop workflow"],
    faqs: [
      { question: "Do DTF shops need vector files?", answer: "Not always, but vector artwork makes scaling, cleanup, and production handoff easier for many jobs." },
      { question: "Can this help with customer-supplied files?", answer: "Yes. DesaynClaw helps clean up imperfect PNG or JPG files before production." },
    ],
    relatedSlugs: ["sublimation-vector", "screen-printing-vector", "logo-to-svg", "image-upscaler"],
  },
  {
    slug: "screen-printing-vector",
    title: "Screen Printing Vector Prep",
    description: "Convert logos and apparel artwork into scalable SVG files for screen printing setup, separations, and design cleanup.",
    audience: "screen printers, apparel shops, and logo designers",
    intent: "Prepare cleaner vector artwork for screen print production.",
    primaryUseCase: "Create scalable art from customer logos and low-resolution apparel graphics.",
    features: ["SVG export", "Logo cleanup", "Print-ready scaling", "Artwork preparation"],
    faqs: [
      { question: "Is SVG useful for screen printing?", answer: "SVG can be useful as a scalable source format before artwork cleanup, separations, and print setup." },
      { question: "Can I vectorize shirt artwork?", answer: "Yes. DesaynClaw can trace shirt artwork from PNG or JPG into SVG output." },
    ],
    relatedSlugs: ["dtf-printing-vector", "logo-to-svg", "png-to-svg"],
  },
  {
    slug: "laser-engraving-vector",
    title: "Laser Engraving Vector Prep",
    description: "Prepare logos, badges, signs, and artwork as SVG vectors for laser engraving and cutting workflows.",
    audience: "laser engraving shops, sign makers, and custom product sellers",
    intent: "Create scalable vector artwork from raster sources before engraving setup.",
    primaryUseCase: "Turn logos and artwork into cleaner SVG files for engraving preparation.",
    features: ["SVG tracing", "Logo cleanup", "High-contrast artwork prep", "Production handoff"],
    faqs: [
      { question: "Can laser engravers use SVG?", answer: "Many laser workflows support SVG or can import vector artwork into setup software." },
      { question: "Can DesaynClaw clean logo edges?", answer: "DesaynClaw can improve and trace logo artwork to create a cleaner vector starting point." },
    ],
    relatedSlugs: ["logo-to-svg", "sign-making-vector", "vectorize-logo"],
  },
  {
    slug: "sign-making-vector",
    title: "Sign Making Vector Prep",
    description: "Convert logos and business artwork into SVG vectors for vinyl signs, decals, storefront graphics, and production design.",
    audience: "sign shops, vinyl cutters, and local print businesses",
    intent: "Prepare clean scalable artwork for signage and vinyl production.",
    primaryUseCase: "Vectorize customer logos before producing decals, signs, and storefront graphics.",
    features: ["Logo to SVG", "Vinyl-ready cleanup", "Scalable artwork", "Print shop workflow"],
    faqs: [
      { question: "Why do sign shops need vector artwork?", answer: "Vector artwork scales cleanly for decals, signs, banners, and storefront graphics." },
      { question: "Can I convert a customer screenshot?", answer: "Screenshots can be traced, but higher-quality source files produce cleaner SVG results." },
    ],
    relatedSlugs: ["laser-engraving-vector", "logo-to-svg", "cricut-svg"],
  },
];

export function getProgrammaticPage(slug) {
  return programmaticPages.find((page) => page.slug === slug);
}
